spring.application.name=FinalProject
spring.datasource.url=jdbc:mysql://localhost:3306/jupiter
spring.datasource.username=root
spring.datasource.password=babca2-ciwgIb-hivfen
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false