spring.application.name=FinalProject
spring.datasource.username=root
spring.datasource.password=babca2-ciwgIb-hivfen
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false